./train_adda.sh /home/vishrutsgoyal/CD29_MSC_20x_PC /home/vishrutsgoyal/CD29_MSC_20x_BF ./logCD29_PC_layer_w3 ./baseline_CD29_PC.ckpt "--max_epochs 6 --weight_id 3"
./train_adda.sh /home/vishrutsgoyal/CD29_MSC_20x_PC /home/vishrutsgoyal/CD29_MSC_20x_BF ./logCD29_PC_layer_w4 ./baseline_CD29_PC.ckpt "--max_epochs 6 --weight_id 4"
./train_adda.sh /home/vishrutsgoyal/CD29_MSC_20x_PC /home/vishrutsgoyal/CD29_MSC_20x_BF ./logCD29_PC_layer_w5 ./baseline_CD29_PC.ckpt "--max_epochs 6 --weight_id 5"
./train_adda.sh /home/vishrutsgoyal/CD29_MSC_20x_PC /home/vishrutsgoyal/CD29_MSC_20x_BF ./logCD29_PC_layer_w6 ./baseline_CD29_PC.ckpt "--max_epochs 6 --weight_id 6"
./train_adda.sh /home/vishrutsgoyal/CD29_MSC_20x_PC /home/vishrutsgoyal/CD29_MSC_20x_BF ./logCD29_PC_layer_w7 ./baseline_CD29_PC.ckpt "--max_epochs 6 --weight_id 7"
